[zh]
    languageName = "ğŸ‡¨ğŸ‡³ä¸­æ–‡"
    languageCode = "zh-CN"
    weight = 1
    title = "å˜Ÿå›”"
    contentdir = "content/zh/"
[en]
    languageName = "ğŸ‡ºğŸ‡¸English"
    languageCode = "en-US"
    weight = 2
    title =  "ToughMn"
    contentdir = "content/en/"