##########################################
# èœå•é…ç½®

# MemE ä¸»é¢˜æ”¯æŒä»¥ä¸‹å››ç§èœå•ï¼š
# 1. main       é¡¶æ ä¸‹æ–¹ï¼ˆå±…ä¸­å¸ƒå±€ï¼‰æˆ–é‡Œé¢ï¼ˆå¼¹æ€§
#               å¸ƒå±€ï¼‰çš„èœå•æ 
# 2. home       é¦–é¡µçš„åº•éƒ¨é“¾æ¥ï¼ˆé€‚ç”¨äºã€Œè¯—æ„
#               äººç”Ÿã€å’Œã€Œè§†é¢‘ç‰‡æ®µã€å¸ƒå±€ï¼‰
# 3. socials    ç¤¾äº¤æ ï¼ˆå…³äºé¡µé¢çš„æç®€é¡µè„šï¼‰
# 4. links      é“¾æ¥æ ï¼ˆå…³äºé¡µé¢çš„æç®€é¡µè„šï¼‰

# èœå•å†…çš„é…ç½®è¯´æ˜å¦‚ä¸‹ï¼š
# url           é“¾æ¥åœ°å€
# name          æ–‡æœ¬ï¼ˆç•™ç©ºï¼ˆ""ï¼‰åˆ™æ— ï¼‰
# weight        ä½ç½®
# pre           å†…é“¾ï¼ˆinternalï¼‰æˆ–å¤–é“¾ï¼ˆexternalï¼‰
# post          å›¾æ ‡ï¼ˆç•™ç©ºï¼ˆ""ï¼‰åˆ™æ— ï¼‰
# identifier    å›¾æ ‡çš„ Class å
#               ï¼ˆå¯¹äºå¼¹æ€§å¸ƒå±€çš„é¡¶æ æœ‰ä¸‰ä¸ªç‰¹æ®Š
#               çš„å€¼ï¼š`theme-switcher`ã€
#               `lang-switcher`ã€`search`ï¼‰

# [menu]
    ## èœå•æ 
    # [[menu.main]]
    #     url = "/"
    #     name = "é¦–é¡µ"
    #     weight = 1
    #     pre = "internal"
    #     post = "home"
[[main]]
        url = "/zh/posts/"
        name = "å½’æ¡£"
        weight = 2
        pre = "internal"
        post = "archive"
[[main]]   
        url = "/zh/categories/"
        name = "åˆ†ç±»"
        weight = 3
        pre = "internal"
        post = "th"
[[main]]   
        url = "/zh/tags/"
        name = "æ ‡ç­¾"
        weight = 4
        pre = "internal"
        post = "tags"
[[main]]   
        url = "/zh/about/"
        name = "å…³äº"
        weight = 5
        pre = "internal"
        post = "user-circle"
[[main]]   
        weight = 7
        identifier = "theme-switcher"
[[main]]   
        weight = 6
        identifier = "lang-switcher"
[[main]]   
        url = "/zh/bbtalk/"
        name = "ğŸ˜‚å“”å“”"
        weight = 1
        pre = "internal"